services:
  app:
    container_name: golang_clean_architecture_app
    build:
      context: .
      dockerfile: backend/containers/golang/Dockerfile
    ports:
      - "8000:8000"
    command: air
    volumes:
      - .:/usr/local/go/src/golang_clean_architecture
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: golang_clean_architecture_db
    build:
      context: .
      dockerfile: backend/containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - backend/.env
    ports:
      - "5432:5432" # デバッグ用
  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: testtest
      MINIO_ROOT_PASSWORD: testtest
      MINIO_SITE_REGION: us-east-1
      MINIO_SERVER_URL: http://localhost:9000
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health" ]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  db_data:
  minio_data:
