services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: backend/containers/golang/Dockerfile
    volumes:
      - ./backend:/usr/local/go/src/golang_clean_architecture/backend
    working_dir: /usr/local/go/src/golang_clean_architecture/backend
    ports:
      - "8000:8000"
    command: air
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    build:
      context: .
      dockerfile: backend/containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - backend/.env
    ports:
      - "5432:5432" # デバッグ用

  nginx:
    container_name: web
    build:
      context: .
      dockerfile: backend/containers/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./backend/containers/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
  minio_data:
